server:
  port: 9004

spring:
  application:
    name: lmall-portal
  profiles:
    active: @profile-env@
    include: common-@profile-env@,stream-@profile-env@


ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 10000

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


